services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: technicalsupport
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://santex:santex@db:5432/santex?schema=public
      JWT_SECRET: changeme
    ports:
      - "3000:3000"
      - "5173:5173"
    depends_on:
      - db
    command: pnpm dev

volumes:
  postgres-data: